apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: prod
  name: subscription-batch
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: subscription-batch
              image: nowgnas/bb-subscription-batch:latest  # Use a Docker image with curl installed
              env:
                - name: USE_PROFILE
                  value: prod
                - name: NOW
                  value: $(date +"%Y%m%d")
          restartPolicy: OnFailure
  schedule: "0 23 */1 * *"
