apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-initdb-config
  namespace: prod
data:
  initdb.sql: |
    use payment;
    CREATE TABLE `payment` (
      `payment_id` bigint NOT NULL AUTO_INCREMENT,
      created_at         datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
      is_deleted         bit DEFAULT false          null,
      updated_at         datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
      `order_id` varchar(255) NOT NULL,
      `order_type` varchar(255) NOT NULL,
      `payment_actual_amount` bigint NOT NULL,
      `payment_cid` varchar(255) NOT NULL,
      `payment_status` varchar(255) NOT NULL,
      `payment_tid` varchar(255) NOT NULL,
      `payment_type` varchar(255) NOT NULL,
      `user_id` bigint NOT NULL,
      PRIMARY KEY (`payment_id`),
      UNIQUE KEY `UK_mf7n8wo2rwrxsd6f3t9ub2mep` (`order_id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

    CREATE TABLE `subscription` (
      `subscription_id` bigint NOT NULL AUTO_INCREMENT,
      created_at         datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
      is_deleted         bit DEFAULT false          null,
      updated_at         datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
      `end_date` datetime(6) DEFAULT NULL,
      `order_subscription_id` varchar(255) NOT NULL,
      `payment_date` datetime(6) NOT NULL,
      `phone_number` varchar(255) NOT NULL,
      `start_date` datetime(6) NOT NULL,
      `subscription_cid` varchar(255) NOT NULL,
      `subscription_quantity` bigint NOT NULL,
      `subscription_sid` varchar(255) NOT NULL,
      `subscription_tid` varchar(255) NOT NULL,
      `subscription_total_amount` bigint NOT NULL,
      `user_id` bigint DEFAULT NULL,
      PRIMARY KEY (`subscription_id`),
      UNIQUE KEY `UK_82ndb8oqwe4oe6pgkxnbdlb0m` (`order_subscription_id`),
      UNIQUE KEY `UK_9yssni9rvd0j4fihx4bskvk74` (`subscription_sid`),
      UNIQUE KEY `UK_h7sppc50by4dbuxwg5s4k97uf` (`subscription_tid`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

    CREATE TABLE `subscription_records` (
      `subscription_records_id` bigint NOT NULL AUTO_INCREMENT,
      created_at         datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
      is_deleted         bit DEFAULT false          null,
      updated_at         datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
      `delivery_id` bigint DEFAULT NULL,
      `subscription_total_amount` bigint NOT NULL,
      `subcription_id` bigint DEFAULT NULL,
      PRIMARY KEY (`subscription_records_id`),
      UNIQUE KEY `UK_4bnpojik2bixyop9h94o4gsd3` (`delivery_id`),
      KEY `FKsrn1sexqeydd9kmny4ctc9sml` (`subcription_id`),
      CONSTRAINT `FKsrn1sexqeydd9kmny4ctc9sml` FOREIGN KEY (`subcription_id`) REFERENCES `subscription` (`subscription_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
