apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-green
  namespace: prod
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
      color: green
  template:
    metadata:
      labels:
        app: auth-service
        color: green
    spec:
#      nodeSelector:
#        nodegroup: cloud2
      containers:
        - name: auth-service
          image: nowgnas/bb-auth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "300Mi"
          env:
            - name: USE_PROFILE
              value: "prod"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 2
          # 애플리케이션이 정상 상태를 유지하고 있는지 지속해서 검사
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 2
      restartPolicy: Always

