apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: prod
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      nodeSelector:
        nodegroup: util
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - name: mongodb
              containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          resources:
            requests:
              memory: "256Mi"
#              cpu: "250m"
#            limits:
#              memory: "300Mi"
#              cpu: "300m"
          # 애플리케이션이 시작된 뒤 초기화 작업이 마무리되어 준비되었는지 검사
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 20
            periodSeconds: 20
          # 애플리케이션이 정상 상태를 유지하고 있는지 지속해서 검사
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 20
            periodSeconds: 20
#        - name: mongodb-exporter
#          image: percona/mongodb_exporter:latest
#          env:
#            - name: MONGODB_URI
#              value: "mongodb://localhost:27017"  # Update with your MongoDB connection string
#          ports:
#            - name: mongodb-exporter
#              containerPort: 9216
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: pvc-mongodb
