apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: prod
  name: pickup-check
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-container
              image: lucashalbert/curl:latest  # Use a Docker image with curl installed
              args:
                - "http://order-service:8900/client/change"
          restartPolicy: OnFailure
  schedule: "*/30 * * * *"
