apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: prod
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      nodeSelector:
        nodegroup: cloud3
      securityContext:
        runAsUser: 0
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - name: prometheus
              containerPort: 9090
          resources:
            requests:
              memory: "350Mi"
              cpu: "250m"
            limits:
              memory: "400Mi"
              cpu: "300m"
          volumeMounts:
            - name: prometheus-service-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: prometheus-service-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: prod
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /metrics
  labels:
    app: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: prod
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      scrape_timeout: 9s
      evaluation_interval: 10s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: [ 'localhost:9090' ]
      
      - job_name: 'apigateway-service'
        static_configs:
          - targets: [ 'apigateway-service:8000' ]
        metrics_path: '/actuator/prometheus'
      
      - job_name: 'auth-service'
        static_configs:
          - targets: [ 'auth-service:9000' ]
        metrics_path: '/actuator/prometheus'
      
      - job_name: 'delivery-service'
        static_configs:
          - targets: [ 'delivery-service:8300' ]
        metrics_path: '/actuator/prometheus'
      
      - job_name: 'giftcard-service'
        static_configs:
          - targets: [ 'giftcard-service:9100' ]
        metrics_path: '/actuator/prometheus'
      
      - job_name: 'notification-service'
        static_configs:
          - targets: [ 'notification-service:8400' ]
        metrics_path: '/actuator/prometheus'
      
      - job_name: 'order-service'
        static_configs:
          - targets: [ 'order-service:8900' ]
        metrics_path: '/actuator/prometheus'
      
      - job_name: 'orderquery-service'
        static_configs:
          - targets: [ 'orderquery-service:9900' ]
        metrics_path: '/actuator/prometheus'
      
      - job_name: 'payment-service'
        static_configs:
          - targets: [ 'payment-service:8100' ]
        metrics_path: '/actuator/prometheus'
      
      - job_name: 'product-service'
        static_configs:
          - targets: [ 'product-service:8800' ]
        metrics_path: '/actuator/prometheus'
      
      - job_name: 'store-service'
        static_configs:
          - targets: [ 'store-service:8700' ]
        metrics_path: '/actuator/prometheus'
      
      - job_name: 'user-service'
        static_configs:
          - targets: [ 'user-service:8600' ]
        metrics_path: '/actuator/prometheus'
      
      - job_name: 'wishlist-service'
        static_configs:
          - targets: [ 'wishlist-service:8500' ]
        metrics_path: '/actuator/prometheus'

      - job_name: 'mongodb'
        static_configs:
          - targets: ['mongodb-exporter:9216']