apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-blue
  namespace: prod
  labels:
    app: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
      color: blue
  template:
    metadata:
      labels:
        app: product-service
        color: blue
    spec:
      nodeSelector:
        nodegroup: cloud
      containers:
        - name: product-service
          image: nowgnas/bb-product:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8800
          resources:
            requests:
              memory: "300Mi"
          env:
            - name: USE_PROFILE
              value: "prod"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8800
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 2
          # 애플리케이션이 정상 상태를 유지하고 있는지 지속해서 검사
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8800
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 2
      restartPolicy: Always

