apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service-green
  namespace: prod
  labels:
    app: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
      color: green
  template:
    metadata:
      labels:
        app: delivery-service
        color: green
    spec:
      containers:
        - name: delivery-service
          image: nowgnas/bb-delivery:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8300
          resources:
            requests:
              memory: "250Mi"
          env:
            - name: USE_PROFILE
              value: "prod"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8300
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 2
          # 애플리케이션이 정상 상태를 유지하고 있는지 지속해서 검사
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8300
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 2
      restartPolicy: Always

